import Head from "next/head";

const GlobalHead = () => {
  return (
    <Head>
      <title>Ateliê Doce Brincadeiro</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
    </Head>
  );
};
export default GlobalHead;
